### ISSUE TITLE
One liner fix? IOS 10

### ISSUE THREAD

**Issue by Mradr** [dinosec/iphone-dataprotection#10]
So looking at the difference between the new pull request that included the backup10.py file, it looks like the only big differences at this point is just this one line of code:
key = kb.unwrapKeyForClass(record.protection_class, record.encryption_key[4:])

I guess the question where is it pulling information and if there is a way to link it back?

**Comment by lcfr123** [comment]
You're probably right. The Manifest.db contains a 'file' column that has some binary data, most likely the info needed to decrypt the corresponding file for the record. Haven't looked into it yet, nor found any info about it on the internet...

**Comment by Mradr** [comment]
Do you have a IRC channel we can chat in do you?

Yea, I been trying to find a way to do the same and had already half this information rewritten. Saw your fix some of the missing information I didn't understand from the older backup4 file.

So the binary data is just a plist within the blob field. Once you read that you get the following lines from it: 
    pl = readPlistFromString(row[4])
    if 'EncryptionKey' in pl["$objects"][1]:
        print(pl["$objects"][1])

{'LastStatusChange': 1479020043, 'LastModified': 1479020043, '$class': Uid(6), 'UserID': 501, 'GroupID': 0, 'ProtectionClass': 4, 'InodeNumber': 74354, 'Birth': 1479020043, 'RelativePath': Uid(2), 'Mode': 33188, 'EncryptionKey': Uid(4), 'Digest': Uid(3), 'Size': 0}

from there I was about to do this:
    if "EncryptionKey" in pl["$objects"][1] is not None and kb:
        key = kb.unwrapKeyForClass(pl["$objects"][1]["ProtectionClass"], pl["$objects"][1]["EncryptionKey"])

but as you see, the line turns UID(X) and that is where I have a problem. I'm not sure where Uid(x) returns to. If we can figure that out - then the rest is easy to fix.

**Comment by lcfr123** [comment]
The 'file' blob column seems different between an encrypted backup and an un-encrypted backup. It looks like base64 encoded, at least in the backup I'm looking at. Also the encrypted backup has 'salt' and 'passwordHash' Properties. Any ideas how to read the Plist in this case?

The UID(n) probably refers to pl["$objects"][n], for nested objects.

**Comment by Mradr** [comment]
Looks like it's already fix:)

but also to ask - how would one go the other way around and encrypt the file back?

**Comment by lcfr123** [comment]
I tried the new code, but it does NOT seem to decrypt my backup. Latest version of iOS 10 and iTunes... No error is given, but the files stay garbage. Or am I missing something here?

**Comment by Mradr** [comment]
I haven't tried it all 100% but it did seem to decrypt some of the files I tested. Any file in mind didn't for you?

**Comment by Mradr** [comment]
Here's what I am using to re - encrypt the file. Maybe someone can check it out and make sure it works as well? Also - need to a way to update the hash once they made changes. Looks like maybe we're lacking a way to update the database.db file?

```
   def _encrypt_file(self, filename, record, output_path):
         # adjust output file name
        if record.is_symbolic_link():
            out_file = record.target
        else:
            out_file = record.relative_path

        try:
            f1 = file(os.path.join(self.backup_path, filename[:2], filename), 'rb')

        except:
            warn("File %s (%s) has not been found" % (os.path.join(filename[:2] ,filename), record.relative_path))
            return

        # write output file
        output_path = os.path.join(output_path, filename[:2], filename)
        ensure_dir_exists(output_path)
        print("Writing %s" % output_path)
        f2 = file(output_path, 'wb')

        aes = None

        if record.encryption_key is not None and self.keybag:
            key = self.keybag.unwrapKeyForClass(record.protection_class, record.encryption_key[4:])
            aes = AES.new(key, AES.MODE_CBC, "\x00"*16)

        while True:
            data = f1.read(8192)
            if not data:
                break
            if aes:
                if len(data) == 0 or len(data) % AES.block_size != 0:
                    padding_length = (AES.block_size - len(data) % AES.block_size) or AES.block_size
                    data += padding_length * chr(padding_length)
                data = aes.encrypt(data)
            f2.write(data)

        f1.close()
        f2.close()
```

**Comment by dinosec** [comment]
@Mradr @lcfr123 May you please confirm if this issue is fixed with pull request #12? Thanks.

**Comment by lcfr123** [comment]
Together with pending pull request #15 (workaround for flags == 16), I can now decrypt and extract again.

**Comment by dinosec** [comment]
Thanks!
