### ISSUE TITLE
sqlite3.DatabaseError: file is encrypted or is not a database

### ISSUE THREAD

**Issue by bacoboy** [dinosec/iphone-dataprotection#14]
Following on from conversation in #13 and #10, I wasn't sure if this was the same or different problem so posting as a separate issue:

```
% python ./backup_tool.py /Users/shoffman/Library/Application\ Support/MobileSync/Backup/6460815e649d545617c60b38ff4efe459c32c935/
Device Name : sPhone6
Display Name : sPhone6
Last Backup Date : 2016-12-28 01:23:50
IMEI : XXXXXXXXXXX
Serial Number : XXXXXXXXXX
Product Type : iPhone7,1
Product Version : 10.2
iTunes Version : 12.5.4.42
Extract backup to /Users/shoffman/Library/Application Support/MobileSync/Backup/6460815e649d545617c60b38ff4efe459c32c935_extract ? (y/n)
y
Backup is encrypted
Enter backup password :
XXXXXXXXXXXXXXXXXXXXXXXXXX
Traceback (most recent call last):
  File "./backup_tool.py", line 104, in <module>
    main()
  File "./backup_tool.py", line 101, in main
    extract_backup(backup_path, output_path)
  File "./backup_tool.py", line 54, in extract_backup
    manifset_db = ManifestDB(backup_path)
  File "/Users/shoffman/workspace/iphone-dataprotection/python_scripts/backups/backup10.py", line 94, in __init__
    for record in cursor.execute("SELECT fileID, domain, relativePath, flags, file FROM Files"):
sqlite3.DatabaseError: file is encrypted or is not a database
```

This was using commit 241e52f.

Happy to help debug if somebody more familiar with the codebase can assist...

**Comment by lcfr123** [comment]
Confirm.

iOS 10.1.1 with iTunes 12.5.3.17 works as expected.
iOS 10.2 with iTunes 12.5.4.42 has the problem you describe.

**Comment by conrado** [comment]
iOS 10.2 with iTunes 12.5.4.42 also has a problem here

**Comment by angelXwind** [comment]
iOS 10.2 with iTunes 12.5.3.16 also experiences the same problem — seems like the issue here is possibly not the iTunes version, but rather iOS 10.2.

**Comment by bkerler** [comment]
Here are details and fixes for this issue : https://github.com/horrorho/InflatableDonkey/issues/41
Seems keybag structure and pbkdf scheme has changed.

**Comment by tnull** [comment]
Hello,
I'm still experiencing the same issue as the OP. Is it still worked on? Or should it already be fixed, as https://github.com/dinosec/iphone-dataprotection/commit/f408bf964d0dcefc992e75687f61fba1f8416db5 was done after this conversation?

**Comment by angelXwind** [comment]
Can confirm pull request #18 works fine for me, decrypting an encrypted iOS 10.2 backup.

**Comment by tnull** [comment]
I can also confirm this! Worked like a charm! Thanks!
