### ISSUE TITLE
Unicode encode error, and a little direction

### ISSUE THREAD

**Issue by headygains** [dinosec/iphone-dataprotection#16]
I've never delved into iOS, but my girlfriend made a backup of her device and its encrypted and she has forgotten the key she encrypted it with. I'm going over the code for backup_tool.py and I'm not sure it's setup to decrypt a backup out of the box. Does the current backup_tool.py support iOS 9.x backups? 

My actual issue at the moment, a UnicodeDecodeError when parsing showlist, should I just add ignore to the Unicode call or is it something more than that?

**Comment by uberhitzt** [comment]
> Does the current backup_tool.py support iOS 9.x backups?

Yes, but if the backup is encrypted, you will need the password. Perhaps you can brute force the password.

**Comment by dinosec** [comment]
Closing this issue due to the lack of activity or extra details (it can be reopened later if required).
