### ISSUE TITLE
seemingly does not work with ios10 backup created with itunes 12.5.1.21

### ISSUE THREAD

**Issue by astroboy2** [dinosec/iphone-dataprotection#5]
backup4.py tries to open "Manifest.mbdb", but this file seems to have been changed to "Manifest.db". symlinking the file results in the exception "bad mbdb signature", so looks like something has really changed.

**Comment by ekristen** [comment]
It's actually a sqlite database now, and there are now a number of plist files in the backup directory

**Comment by astroboy2** [comment]
so this is a pretty big change.

**Comment by ekristen** [comment]
Its a change, as long as the encryption and stuff hasn't changed the files are just slightly in a different directory structure and its using a straight up sqlite database. I really need to get this working though because a few of my apps didn't restore their data properly.

**Comment by dinosec** [comment]
The iTunes backup format has significantly changed from iOS 9 to iOS 10 (and the associated iTunes versions; see comments above and more info at http://smarterforensics.com/2016/09/a-glimpse-of-ios-10-from-a-smartphone-forensic-perspective/). 

The old iphone-dataprotection tools (cloned from the original version in this GitHub project) do not support the new iOS 10 format, unless someone decides to update them ;)
